export const COMPARISONS_ADD_REQUEST = 'COMPARISONS_ADD_REQUEST';
export const COMPARISONS_ADD_SUCCESS = 'COMPARISONS_ADD_SUCCESS';
export const COMPARISONS_ADD_FAIL = 'COMPARISONS_ADD_FAIL';
export const COMPARISONS_ADD_RESET = 'COMPARISONS_ADD_RESET';

export const COMPARISONS_REMOVE_REQUEST = 'COMPARISONS_REMOVE_REQUEST';
export const COMPARISONS_REMOVE_SUCCESS = 'COMPARISONS_REMOVE_SUCCESS';
export const COMPARISONS_REMOVE_FAIL = 'COMPARISONS_REMOVE_FAIL';
export const COMPARISONS_REMOVE_RESET = 'COMPARISONS_REMOVE_RESET';

export const COMPARISONS_LIST_MY_REQUEST = 'COMPARISONS_LIST_MY_REQUEST';
export const COMPARISONS_LIST_MY_SUCCESS = 'COMPARISONS_LIST_MY_SUCCESS';
export const COMPARISONS_LIST_MY_FAIL = 'COMPARISONS_LIST_MY_FAIL';