export const REVIEWS_REMOVE_REQUEST = 'REVIEWS_REMOVE_REQUEST';
export const REVIEWS_REMOVE_SUCCESS = 'REVIEWS_REMOVE_SUCCESS';
export const REVIEWS_REMOVE_FAIL = 'REVIEWS_REMOVE_FAIL';
export const REVIEWS_REMOVE_RESET = 'REVIEWS_REMOVE_RESET';

export const REVIEWS_LIST_MY_REQUEST = 'REVIEWS_LIST_MY_REQUEST';
export const REVIEWS_LIST_MY_SUCCESS = 'REVIEWS_LIST_MY_SUCCESS';
export const REVIEWS_LIST_MY_FAIL = 'REVIEWS_LIST_MY_FAIL';