export const SUBSCRIBE_INITIATE_REQUEST = 'SUBSCRIBE_INITIATE_REQUEST';
export const SUBSCRIBE_INITIATE_SUCCESS = 'SUBSCRIBE_INITIATE_SUCCESS';
export const SUBSCRIBE_INITIATE_FAILURE = 'SUBSCRIBE_INITIATE_FAILURE';
export const SUBSCRIBE_INITIATE_RESET = 'SUBSCRIBE_INITIATE_RESET';

export const SUBSCRIBE_CONFIRM_REQUEST = 'SUBSCRIBE_CONFIRM_REQUEST';
export const SUBSCRIBE_CONFIRM_SUCCESS = 'SUBSCRIBE_CONFIRM_SUCCESS';
export const SUBSCRIBE_CONFIRM_FAILURE = 'SUBSCRIBE_CONFIRM_FAILURE';

export const UNSUBSCRIBE_CONFIRM_REQUEST = 'UNSUBSCRIBE_CONFIRM_REQUEST';
export const UNSUBSCRIBE_CONFIRM_SUCCESS = 'UNSUBSCRIBE_CONFIRM_SUCCESS';
export const UNSUBSCRIBE_CONFIRM_FAILURE = 'UNSUBSCRIBE_CONFIRM_FAILURE';
