# Generated by Django 4.2.5 on 2023-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
