# Generated by Django 4.2.5 on 2023-10-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_brand_category_rating_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
