# Generated by Django 4.2.5 on 2023-10-23 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
