# Generated by Django 4.2.5 on 2023-11-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='/customer.jpg', null=True, upload_to=''),
        ),
    ]
