# Generated by Django 4.2.5 on 2023-11-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='FeedbackSubject',
        ),
    ]
