# Generated by Django 4.2.5 on 2023-11-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
